---
# Конфигурация ansible-lint для роли system-update
skip_list:
  - role-name  # Пропустить проверку имени роли для локальных ролей
warn_list:
  - role-name  # Также добавить в warn_list на случай, если skip_list не работает
