---
# Глобальная конфигурация Molecule для роли system-update
# Этот файл используется для настройки Molecule на уровне роли

# Настройки по умолчанию для всех сценариев
defaults:
  # Время ожидания для операций
  timeout: 30
  
  # Логирование
  log: true
  log_level: info
